paths:
  data_csv: "./data/raw_data_csv"
  data_txt: "./data/raw_data_txt"
  data_clean: "./data/clean"

files:
  experiment: "df_final_experiment_clients.txt"
  demo: "df_final_demo.txt"
  web1: "df_final_web_data_pt_1.txt"
  web2: "df_final_web_data_pt_2.txt"


